### ISSUE TITLE
img ohne alt und title

### ISSUE THREAD

**Issue by sascha-mueller** [christianbarkowsky/coverpicture#6]
Hallo,
obwohl im Template folgendes hinterlegt ist:

` alt="<?php echo $this->pagetitle; ?>" title="<?php echo $this->pagetitle; ?>`
wird das Bild alt- und title-Attribut ohne ausgegeben.

`<img alt="" title="">`

Vielleicht kannst Du mal schauen woran es liegt und das beheben.
Danke und Gruß,
Sascha

**Comment by christianbarkowsky** [comment]
@sascha-mueller ich kann das leider nicht nachstellen ... contao 3.5.4 & coverpicture 1.2.3

Könnte es sein, das deine Seite keinen Seitentitel hat?!

**Comment by sascha-mueller** [comment]
Da die Seite den Titel aus dem Namen übernimmt, wenn ich keinen Titel vergebe und ich den Namen vergeben muss, heißt die Antwort streng genommen nein.
Allerdings habe ich das Feld Titel nicht explizit befüllt.

**Comment by sascha-mueller** [comment]
Danke für die Aufklärung.
Ich weis zwar noch nicht wieso es bei mir nach dem Update nicht funktionierte, ich konnte jedoch bei Dir sehen, dass er den Seitentitel als alt/title für das Bild übernimmt.
Leider muss meine Lösung etwas anders aussehen, weshalb sich auch hier keine weitere Recherche lohnt.

Danke @christianbarkowsky für das sehr schnelle Kümmern und Zurückmelden.
Support: 1 mit *
